import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <nav className="flex flex-row justify-center">
          <Link className="px-4 py-1 hover:bg-sky-300" href="/">HOME</Link>
          <Link className="px-4 py-1 hover:bg-sky-300" href="/SSG">SSG</Link>
          <Link className="px-4 py-1 hover:bg-sky-300" href="/ISR">ISR</Link>
          <Link className="px-4 py-1 hover:bg-sky-300" href="/SSR">SSR</Link> 
          <Link className="px-4 py-1 hover:bg-sky-300" href="/CSR">CSR</Link>
        </nav>
        {children}
        </body>
    </html>
  );
}
